### ISSUE TITLE
Can't resolve 'ng-dropzone'

### ISSUE THREAD

**Issue by BjornMelgaard** [thatisuday/ng-dropzone#25]
```
ERROR in ./src/app.module.js
Module not found: Error: Can't resolve 'ng-dropzone' in '/home/bjorn/projects/*****/fe/src'
 @ ./src/app.module.js 75:18-40
 @ ./src/app.js
 @ multi babel-polyfill webpack/hot/dev-server ./src/app.js
```

because `  "main": "index.js"` in `node_modules/ng-dropzone/package.json`, but must be `./dist/ng-dropzone.js`

**Comment by thatisuday** [comment]
If you ware using Dropzone with npm or webpack, please use this package https://www.npmjs.com/package/angular2-dropzone-wrapper
